#!/bin/sh
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Matthias Wenskus <matthias.wenskus@jabbs.de>
# @copyright Copyright (c) 2015 Matthias Wenskus
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e 

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

# todo: why this doesn´t work?
#OMV_CRONSCRIPTS_DIR = ${OMV_CRONSCRIPTS_DIR:-"/etc/cron.d/"}
#echo  ${OMV_CRONSCRIPTS_DIR}

#creating config file 
xmlstarlet sel -t -m "//services/dyndns" \
  -v "concat('username = ',username)" -n \
  -v "concat('password = ',password)" -n \
  -v "concat('hostname = ',hostname)" -n \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > /var/lib/openmediavault/dyndns/config.ini

  
 #todo  delete cron file and only if enabled =1 create a new script
 
enabled = $(xmlstarlet sel -t -m "//services/dyndns"  -v "enable" ${OMV_CONFIG_FILE} )
 
if [ $enabled -eq 1 ]
then
#creating cron file
xmlstarlet sel -t -m "//services/dyndns" \
  -o "SHELL=/bin/sh" -n \
  -o "PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin" -n \
  -o "# m h dom mon dow user    command" -n \
  -o "SHELL=/bin/sh" -n \
  -v "concat('*/',interval,' * * * * root /var/lib/openmediavault/dyndns/dynDnsUpdater >/dev/null 2>&1 ')" -n \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > /etc/cron.d/openmediavault-dyndnsupdater

  chmod 644 /etc/cron.d/openmediavault-dyndnsupdater
  
else
  rm  /etc/cron.d/openmediavault-dyndnsupdater
fi
 





