#!/bin/sh
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Matthias Wenskus <matthias.wenskus@jabbs.de>
# @copyright Copyright (c) 2015 Matthias Wenskus
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e  

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions


CRON_DIR="/etc/cron.d/"
OMV_DYNDNS_UPDATE_SCRIPT_DIR="/var/lib/openmediavault/dyndns"


enabled=$(xmlstarlet sel -t -m "//services/dyndns"  -v "enable" ${OMV_CONFIG_FILE} )
 
if [ $enabled -eq 1 ]
then

#creating config file 
xmlstarlet sel -t -m "//services/dyndns" \
  -v "concat('username:',username)" -n \
  -v "concat('password:',password)" -n \
  -v "concat('hostname:',hostname)" -n \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_DYNDNS_UPDATE_SCRIPT_DIR}/config.ini

  chmod 600 ${OMV_DYNDNS_UPDATE_SCRIPT_DIR}/config.ini
  
#creating cron file
xmlstarlet sel -t -m "//services/dyndns" \
  -o "SHELL=/bin/sh" -n \
  -o "PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin" -n \
  -o "# m h dom mon dow user    command" -n \
  -o "SHELL=/bin/sh" -n \
  -v "concat('*/',interval,' * * * * root ${OMV_DYNDNS_UPDATE_SCRIPT_DIR}/dynDnsUpdater >/dev/null 2>&1 ')" -n \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${CRON_DIR}/openmediavault-dyndnsupdater

chmod 644 ${CRON_DIR}/openmediavault-dyndnsupdater
  
else
  rm -f /${CRON_DIR}/openmediavault-dyndnsupdater
  rm -f ${OMV_DYNDNS_UPDATE_SCRIPT_DIR}/dyndns/config.ini
fi
