#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_DYNDNS_UPDATE_SCRIPT_DIR="/var/lib/openmediavault/dyndns"
CRON_DIR="/etc/cron.d/"

SERVICE_XPATH_NAME="dyndns"
SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

case "$1" in
    purge)
        if omv_config_exists ${SERVICE_XPATH}; then
            omv_config_delete ${SERVICE_XPATH}
        fi

	rm -f ${CRON_DIR}/openmediavault-dyndnsupdater
	rm -f ${OMV_DYNDNS_UPDATE_SCRIPT_DIR}/config.ini
	rm -f ${OMV_DYNDNS_UPDATE_SCRIPT_DIR}/dynDnsUpdater
	rmdir ${OMV_DYNDNS_UPDATE_SCRIPT_DIR}
    ;;

    remove)
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
