#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

SERVICE_XPATH_NAME="dyndns"
SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

case "$1" in
    purge)
        if omv_config_exists ${SERVICE_XPATH}; then
            omv_config_delete ${SERVICE_XPATH}
        fi

	rm -f /etc/cron.d/openmediavault-dyndnsupdater
	rm -f /var/lib/openmediavault/dyndns/config.ini
	rm -f /var/lib/openmediavault/dyndns/dynDnsUpdater
	rmdir /var/lib/openmediavault/dyndns
    ;;

    remove)
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
